FROM python:3.12.0-alpine3.17

# Defines the working directory for the following operations
WORKDIR /api

# Copies the requirements.txt file to the working directory
COPY requirements.txt requirements.txt

# PIP update
RUN pip install --upgrade pip

# Installs Python dependencies from requirements.txt
RUN pip install -r requirements.txt

# Backend source code copy
COPY . .

EXPOSE 5000
VOLUME /api/logs

# Execution gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:app"]
